### ISSUE TITLE
A question about the version

### ISSUE THREAD

**Issue by chg0901** [alexarchambault/jupyter-scala#141]
Dear friends, 
 
  I am a beginner of spark.Because I think the spark-shell is inconvenience to use, so I want to use spark-shell(scala) with jupyter ipython notebook.

But my scala version is 2.10.4,and my spark version is 1.2.0.

what do you think about it if I git your jupyter scala for the spark work?
I have seen that you said "scala2.10 can be supported",but I do not know how to set up with scala2.10.4

can you give me some advice on the IDE with spark-shell(scala)?

Thanks in advance!

Hong Cheng

email:kwchenghong@gmail.com

**Comment by alexarchambault** [comment]
I stopped compiling for 2.10 in the latest version, by lack of time mostly. It's not too hard to add back support for it though. I'm adding it back for the core of the kernel itself (via https://github.com/alexarchambault/jupyter-kernel/pull/13).

For the spark-related things in 2.10, it may need a bit of work though (as the spark things in jupyter-scala currently rely on the `cli` module of [coursier](https://github.com/coursier/coursier), itself only compiled for 2.11 - the parts that are used by jupyter-scala should be split to a separate module, itself compiled to 2.10).

About spark `1.2`, I have no idea if it still works fine. `1.3` should be fine (the spark things in jupyter-scala used to be compiled against it). You'll have to try and see if it works for `1.2`.

**Comment by chg0901** [comment]
thanks your kind and quickly reply.
I choose this version because this version is same as a text book in my course.
I will try to install spark and Scala again using the version same as your gits.

Thanks again.


Best regards,
Hong Cheng
