### ISSUE TITLE
Wrong answers for flatMap

### ISSUE THREAD

**Issue by cliburn** [alexarchambault/jupyter-scala#2]
```scala
val xs = List(1,2,3)
xs flatMap {x => List(x, x*2)}
```

gives 
```scala
List(1, 2, 3)
```

but
```scala
xs map {x =>List(x, x*2)} flatten
```

gives
```scala
List(1, 2, 2, 4, 3, 6)
```

**Comment by alexarchambault** [comment]
Confirming that too. The only displayed results correspond to the first line entered, so for
```scala
val xs = List(1,2,3)
xs flatMap {x => List(x, x*2)}
```
you get the result of `val xs = List(1,2,3)`, which can be a bit surprising (and needs to be fixed, which I'll do soon).

**Comment by alexarchambault** [comment]
This is now fixed:

![jupyter-scala 2](https://cloud.githubusercontent.com/assets/7063723/7657174/36f740ac-fb30-11e4-860d-e62ec3385236.PNG)
