### ISSUE TITLE
Download as Scala code does not work

### ISSUE THREAD

**Issue by sdwfrost** [alexarchambault/jupyter-scala#26]
Downloading a notebook as Scala code gives a 500 error (internal server error)

```
nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: 'scala'
```

**Comment by alexarchambault** [comment]
I can reproduce... Should be easy to fix. Thanks for the report!

**Comment by queirozfcom** [comment]
Has this been closed? I've just downloaded it and I still can't download files as Scala

**Comment by alexarchambault** [comment]
As a side note, notebooks created with a kernel without the fix need to be saved once (with a fixed kernel), then re-opened for the download-as link to work.
