### ISSUE TITLE
Creating REPL Classes using Reflection

### ISSUE THREAD

**Issue by kmader** [alexarchambault/jupyter-scala#43]
Classes that are created in the REPL cannot be initiated using reflection (they show up with one argument when they should have 0).

A simple example is shown here
A normal class can be created without any problem
```scala
val testBasic = Try{classOf[java.io.ByteArrayOutputStream].newInstance()}
testBasic: scala.util.Try[java.io.ByteArrayOutputStream] = Success()
```

Making the classes in the REPL (even with a few tricks) 
```scala
class TestClassA
object TestObjA {
    class TestClassB
}
object TestObjB {
    class TestClassC
}
```

Works fine with standard methods
```scala
val testA1 = new TestClassA
val testB1 = new TestObjA.TestClassB
import TestObjB._
val testC1 = new TestClassC
testA1: cmd2.INSTANCE.$ref$cmd0.TestClassA = cmd0$$user$TestClassA@65100245
testB1: cmd2.INSTANCE.$ref$cmd0.TestObjA.TestClassB = cmd0$$user$TestObjA$TestClassB@18654dc1
import TestObjB._
testC1: cmd2.INSTANCE.$ref$cmd0.TestObjB.TestClassC = cmd0$$user$TestObjB$TestClassC@54bd18ab
```

but not with reflection
```scala
import scala.util.Try
val testA2 = Try{classOf[TestClassA].newInstance()}
val testB2 = Try{classOf[TestObjA.TestClassB].newInstance()}
val testC2 = Try{classOf[TestClassC].newInstance()}
```

```
testA2: scala.util.Try[cmd4.INSTANCE.$ref$cmd0.TestClassA] = Failure(java.lang.InstantiationException: cmd0$$user$TestClassA)
testB2: scala.util.Try[cmd4.INSTANCE.$ref$cmd0.TestObjA.TestClassB] = Failure(java.lang.InstantiationException: cmd0$$user$TestObjA$TestClassB)
testC1: scala.util.Try[cmd4.INSTANCE.$ref$cmd0.TestObjB.TestClassC] = Failure(java.lang.InstantiationException: cmd0$$user$TestObjB$TestClassC)
```

See a more detailed example [here](https://github.com/4Quant/ImgLib2-Notebooks/blob/master/Create%20Ops.ipynb). A similar problem is listed [here](http://fiji.sc/bugzilla/show_bug.cgi?id=874)

**Comment by kmader** [comment]
An example notebook (https://gist.github.com/kmader/d7299dc542cfab974b80)

**Comment by alexarchambault** [comment]
Adding `import special.wrap.obj` in the cell defining the classes makes your example work, see https://gist.github.com/alexarchambault/d115ae3585d262f01700. This has the effect of modifying the way the kernel compiles the code of the cell, which in turn makes it easier to use the classes it defines reflectively or with macros.

This ought to be written in a doc somewhere, sorry it's not yet... I guess I'll write one for the next major version of jupyter-scala, which should be soon.

**Comment by kmader** [comment]
Perfect thanks!

**Comment by ctrueden** [comment]
@alexarchambault So, @keithschulze and I are updating the [aforementioned notebooks](https://github.com/4Quant/ImgLib2-Notebooks) to the latest version of the Jupyter Scala kernel, and the `import special.wrap.obj` declaration seems to no longer function after your big refactoring. Is there an equivalent way of achieving the same goal?
