### ISSUE TITLE
Kernel won't list in ipython

### ISSUE THREAD

**Issue by moxpower** [alexarchambault/jupyter-scala#56]
After running the jupyter-scala file I get:

```
Error: Could not find or load main class files.jupyter-scala_2.11.6-0.2.0-SNAPSHOT.icon-mac.png
logout

[Process completed]
```
Afterwards the kernel doesn't list in the jupyter (ipython) kernels. How could I fix this?

**Comment by alexarchambault** [comment]
I don't really know at first, but you might have more luck with the new version of the kernel, described at https://github.com/alexarchambault/jupyter-scala/tree/topic/update-readme, whose installation is a bit different.

**Comment by moxpower** [comment]
Thank you! It works now for me as described in the ReadMe (I had to run the curl command twice).

Thanks for the kernel! I appreciate your work.

**Comment by alexarchambault** [comment]
Closing this :)
