### ISSUE TITLE
Having troubles adding Breeze

### ISSUE THREAD

**Issue by bushmanov** [alexarchambault/jupyter-scala#57]
I'am a newbee to Scala/Java and having troubles adding [Breeze](https://github.com/scalanlp/breeze) to `jupyter-scala`.

My assumption is that appending the lines

```
libraryDependencies ++= Seq(
"org.scalanlp" %% "breeze" % "0.11.2",
"org.scalanlp" %% "breeze-natives" % "0.11.2"
)
```
to `build.sbt` should allow me later importing `breeze` into jupyter notebook. But I'm encountering a dozen of errors even when I simply try issuing `sbt` and later `console` commands in the `./jupyter-scala` directory.

Am I doing something wrong and what would be a correct way of adding `Breeze` ?

Thanks!

**Comment by alexarchambault** [comment]
You should follow the instructions in the updated README, these are more straightforward I think.

You should launch a jupyter notebook server then, create a new Scala 2.1x notebook, and add breeze directly from the notebook, like illustrated at https://gist.github.com/alexarchambault/6f7eeffef3ecdf353992.

**Comment by bushmanov** [comment]
It works, thanks!

**Comment by mgorjis** [comment]
When I am trying to run the first block:

```
classpath.add(
 "org.scalanlp" %% "breeze" % "0.11.2",
 "org.scalanlp" %% "breeze-natives" % "0.11.2"
 )
```

I see this error in the jupyter:

```
Compilation Failed
 Main.scala:49: not found: value classpath
 classpath.add(
 ^
```

And thus I can't load breeze. Do you have any idea? Thank you.

**Comment by tinastefaniewenzel** [comment]
Same error here. I correctly specified the build.sbt file, ran sbt update and can import it from the Terminal (after sbt console) and also import it in IntelliJ ideas. 

But I get the `not found: value classpath` error when trying to import it from jupyter

**Comment by alpanchino** [comment]
When I am trying to run the first block:

classpath.add(
"org.scalanlp" %% "breeze" % "0.11.2",
"org.scalanlp" %% "breeze-natives" % "0.11.2"
)

I also have this issue:

Compilation Failed
Main.scala:49: not found: value classpath
classpath.add(
^

**Comment by Roshrini** [comment]
I am also having the same issue. Any advice will be helpful.

**Comment by benqua** [comment]
Running on the same issue (not found: value classpath)
@Roshrini how did you solve it? I see you wrote a few scala notebooks ( https://github.com/Roshrini/mxnet-notebooks/blob/scala-notebooks/scala/tutorials/predict_imagenet_scala.ipynb ) so you obviously managed to solve this issue. Can you help?

**Comment by Roshrini** [comment]
Hi @benqua You can see the instructions related to jupyter-scala installation here in my Readme file: https://github.com/Roshrini/mxnet-notebooks/blob/scala-notebooks/README.md I used version 0.3.x to get this classpath command working.

**Comment by mullerhai** [comment]
import $ivy.`org.scalanlp::breeze:0.13.1`
import $ivy.`org.scalanlp::breeze-natives:0.13.1` 
like this
